### ISSUE TITLE
前排支持下~ 另外希望能增加对 UWP版微信的支持

### ISSUE THREAD

**Issue by gears233** [blackboxo/AutoDeleteFileOnPCWechat#3]
rt，UWP版微信位置一般在：

`C:\Users\用户名\AppData\Local\Packages\TencentWeChatLimited.forWindows10_xxxxxx\LocalCache\Roaming\Tencent文件夹下面`

而这个让普通用户自己找可能就比较麻烦了...

**Comment by blackboxo** [comment]
> rt，UWP版微信位置一般在：
> 
> `C:\Users\用户名\AppData\Local\Packages\TencentWeChatLimited.forWindows10_xxxxxx\LocalCache\Roaming\Tencent文件夹下面`
> 
> 而这个让普通用户自己找可能就比较麻烦了...

好 我看看

**Comment by gears233** [comment]
我发现我好像表述的有点问题，windows 商店里面目前是有两款微信的，一个叫微信for windows ，一个叫 微信（UWP）。我一开始想说的其实是 微信for windows ，这个应该是当初 win32 版本转制而来的，也是版本更新相对新一些的。而另一个  微信（UWP）在更早之前就停止更新了，不过这两者存储数据的目录是类似的，都在
`C:\Users\用户名\AppData\Local\Packages\` 下面，只是一个是 TencentWeChatLimited.forWindows10_xxxxxx 文件夹，一个是TencentWeChatLimited.WeChatUWP_xxxxxx 文件夹。 

不过这个xxxx 的字符不知道是不是统一的，没有查证。

**Comment by blackboxo** [comment]
> 我发现我好像表述的有点问题，windows 商店里面目前是有两款微信的，一个叫微信for windows ，一个叫 微信（UWP）。我一开始想说的其实是 微信for windows ，这个应该是当初 win32 版本转制而来的，也是版本更新相对新一些的。而另一个 微信（UWP）在更早之前就停止更新了，不过这两者存储数据的目录是类似的，都在
> `C:\Users\用户名\AppData\Local\Packages\` 下面，只是一个是 TencentWeChatLimited.forWindows10_xxxxxx 文件夹，一个是TencentWeChatLimited.WeChatUWP_xxxxxx 文件夹。
> 
> 不过这个xxxx 的字符不知道是不是统一的，没有查证。

微信（UWP）我无法下载，微信for windows 我下载了，但是因为我是新的，所以我无法看到具体缓存文件的存储结构，如果方便的话是否可以加我微信 blackboxo，将您的文件目录发给我，感谢。

**Comment by gears233** [comment]
> > 我发现我好像表述的有点问题，windows 商店里面目前是有两款微信的，一个叫微信for windows ，一个叫 微信（UWP）。我一开始想说的其实是 微信for windows ，这个应该是当初 win32 版本转制而来的，也是版本更新相对新一些的。而另一个 微信（UWP）在更早之前就停止更新了，不过这两者存储数据的目录是类似的，都在
> > `C:\Users\用户名\AppData\Local\Packages\` 下面，只是一个是 TencentWeChatLimited.forWindows10_xxxxxx 文件夹，一个是TencentWeChatLimited.WeChatUWP_xxxxxx 文件夹。
> > 不过这个xxxx 的字符不知道是不是统一的，没有查证。
> 
> 微信（UWP）我无法下载，微信for windows 我下载了，但是因为我是新的，所以我无法看到具体缓存文件的存储结构，如果方便的话是否可以加我微信 blackboxo，将您的文件目录发给我，感谢。

微信号啥的可能不大方便，不过我已经发了一份文件目录树到你GitHub显示的默认邮箱里面，请查收。

**Comment by blackboxo** [comment]
已支持 Microsoft Store 下载的微信 for Windows 版本，UWP 版本的文件存储路径中，部分命名规则尚不明确，待有需要再开发，如果有需求的可以提供自己的文件目录树。
