### ISSUE TITLE
英文 windows 7下说找不到微信用户

### ISSUE THREAD

**Issue by redseabay** [blackboxo/AutoDeleteFileOnPCWechat#5]
原因是英文的windows7 的用户目录和中文有区别 ?
英文的是这个样子
c:\Users\xxx\AppData\Roaming\

**Comment by blackboxo** [comment]
请问您的微信哪个版本？Microsoft Store 下载的吗？ 如果可以的话请提供具体的报错信息和文件路径。

**Comment by blackboxo** [comment]
> 原因是英文的windows7 的用户目录和中文有区别 ?
> 英文的是这个样子
> c:\Users\xxx\AppData\Roaming\

请问您的微信哪个版本？Microsoft Store 下载的吗？ 如果可以的话请提供具体的报错信息和文件路径。

**Comment by blackboxo** [comment]
新版本1.1自动识别路径
